FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install --production

# Copy app source
COPY . ./

# Use non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

#vishal vyavahare123

EXPOSE 3000
CMD ["node", "index.js"]
